In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('data/Breast_cancer.csv')

In [3]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [4]:
data.shape

(683, 11)

In [5]:
data['Class'].value_counts()

2    444
4    239
Name: Class, dtype: int64

In [6]:
data['Class'] = data['Class'].map({2:0,4:1})

In [7]:
data.isna().sum()

Sample code number             0
Clump Thickness                0
Uniformity of Cell Size        0
Uniformity of Cell Shape       0
Marginal Adhesion              0
Single Epithelial Cell Size    0
Bare Nuclei                    0
Bland Chromatin                0
Normal Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [8]:
data.dtypes

Sample code number             int64
Clump Thickness                int64
Uniformity of Cell Size        int64
Uniformity of Cell Shape       int64
Marginal Adhesion              int64
Single Epithelial Cell Size    int64
Bare Nuclei                    int64
Bland Chromatin                int64
Normal Nucleoli                int64
Mitoses                        int64
Class                          int64
dtype: object

In [9]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      0  
1           10                3                2        1      0  
2            2                3                1        1      0  
3            4                3                7        1      0  
4            1                3                1        1      0

In [10]:
X = data.drop(['Class','Sample code number'],axis=1)
y = data['Class']

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### importing xgboost

In [12]:
import xgboost as xgb
classifier = xgb.XGBClassifier()  #XGBClassifier object is created
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[84  3]
 [ 1 49]]


0.9708029197080292

In [14]:
from sklearn.model_selection import cross_val_score  #cross validation is used only for scoring
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 3)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))

Accuracy: 95.97 %


### XGBoost Data Matrix

Now you will convert the dataset into an optimized data structure called Dmatrix that XGBoost supports and gives it acclaimed performance and efficiency gains

In [14]:
data_dmatrix = xgb.DMatrix(data=X,label=y)

In [15]:
type(data_dmatrix)

xgboost.core.DMatrix

In [30]:
?xgb.XGBClassifier

In [22]:
params = {"objective":"binary:logistic",'colsample_bytree': 0.3,'learning_rate': 0.1,
                'max_depth': 5, 'alpha': 10}
cv_results = xgb.cv(dtrain=data_dmatrix, params=params, nfold=3,
                    num_boost_round=100,early_stopping_rounds=5,metrics="error", as_pandas=True, seed=123)

In [18]:
?xgb.cv

In [24]:
cv_results

train-error-mean  train-error-std  test-error-mean  test-error-std
0           0.065889         0.006248         0.071734        0.011463
1           0.054172         0.017054         0.061487        0.003479
2           0.053437         0.020157         0.062962        0.002204
3           0.035869         0.008468         0.040994        0.009003
4           0.033676         0.006305         0.038070        0.012584
5           0.034405         0.005754         0.039532        0.010744
6           0.033674         0.003726         0.039532        0.010744
7           0.030021         0.006323         0.038063        0.010927
8           0.032214         0.003756         0.042449        0.010302
9           0.027821         0.005193         0.035139        0.003582
10          0.024894         0.004532         0.035133        0.006171
11          0.020500         0.004154         0.030741        0.006176
12          0.020500         0.004154         0.030741        0.006176
13          0.021232         0.005189         0.032203        0.008243
14          0.021963         0.004754         0.033665        0.007417
15          0.021231         0.002083         0.032203        0.005429
16          0.020498         0.002745         0.029279        0.007440

In [25]:
from sklearn.model_selection import GridSearchCV #GridSearchCV is for parameter tuning

In [31]:
parameters={"objective":["binary:logistic"],'colsample_bytree': [0.3,0.5,0.7,0.9],'learning_rate': [0.1,0.3,0.5,0.7,0.9],
                'max_depth': [5,10], 'alpha': [10],'n_estimators':[6]}

In [32]:
xgb_final = GridSearchCV(classifier, parameters)
xgb_final.fit(X_train,y_train)

GridSearchCV(estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0, gpu_id=-1,
                                     importance_type='gain',
                                     interaction_constraints='',
                                     learning_rate=0.300000012,
                                     max_delta_step=0, max_depth=6,
                                     min_child_weight=1, missing=nan,
                                     monotone_constraints='()',
                                     n_estimators=100, n_jobs=0,
                                     num_parallel_tree=1, random_state=0,
                                     reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, subsample=1,
                                     tree_method='exact', validate_parameters=1,
                            

In [36]:
xgb_final.best_params_

{'alpha': 10,
 'colsample_bytree': 0.5,
 'learning_rate': 0.7,
 'max_depth': 5,
 'n_estimators': 6,
 'objective': 'binary:logistic'}

In [33]:
xgb_final.predict(X_test)

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0])

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = xgb_final.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[84  3]
 [ 4 46]]


0.948905109489051

In [58]:
#END