In [27]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.preprocessing import LabelEncoder

In [16]:
breast_cancer = load_breast_cancer()
X = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)
y = pd.Categorical.from_codes(breast_cancer.target, breast_cancer.target_names)

In [17]:
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [19]:
y

['malignant', 'malignant', 'malignant', 'malignant', 'malignant', ..., 'malignant', 'malignant', 'malignant', 'malignant', 'benign']
Length: 569
Categories (2, object): ['malignant', 'benign']

In [20]:
encoder = LabelEncoder()
binary_encoded_y = pd.Series(encoder.fit_transform(y))

In [21]:
binary_encoded_y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Length: 569, dtype: int64

In [22]:
train_X, test_X, train_y, test_y = train_test_split(X, binary_encoded_y, random_state=1)

In [23]:
?AdaBoostClassifier

In [24]:
classifier = AdaBoostClassifier(
    n_estimators=200
)
classifier.fit(train_X, train_y)

AdaBoostClassifier(n_estimators=200)

In [25]:
y_pred = classifier.predict(test_X) 

In [26]:
confusion_matrix(test_y, y_pred)

array([[86,  2],
       [ 3, 52]])

In [29]:
accuracy_score(test_y,y_pred)*100

96.5034965034965

### GBM

In [30]:
from sklearn.ensemble import GradientBoostingClassifier

In [31]:
?GradientBoostingClassifier

In [32]:
gbm = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,max_depth=1)

In [33]:
gbm.fit(train_X, train_y)

GradientBoostingClassifier(learning_rate=1.0, max_depth=1)

In [34]:
y_pred = gbm.predict(test_X) 

In [35]:
confusion_matrix(test_y, y_pred)

array([[87,  1],
       [ 5, 50]])

In [36]:
accuracy_score(test_y,y_pred)*100

95.8041958041958

In [37]:
import xgboost as xgb
xgb_clf = xgb.XGBClassifier()

In [38]:
xgb_clf.fit(train_X, train_y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [39]:
y_pred = xgb_clf.predict(test_X) 

In [40]:
confusion_matrix(test_y, y_pred)

array([[86,  2],
       [ 4, 51]])

In [41]:
accuracy_score(test_y,y_pred)*100

95.8041958041958

In [8]:
#END