In [1]:
import pandas as pd
import numpy

In [36]:
data = pd.read_csv("data/golf.csv")

In [37]:
data

Outlook  Temp Humidity  Windy Play Golf
0      Rainy   Hot     High  False        No
1      Rainy   Hot     High   True        No
2   Overcast   Hot     High  False       Yes
3      Sunny  Mild     High  False       Yes
4      Sunny  Cool   Normal  False       Yes
5      Sunny  Cool   Normal   True        No
6   Overcast  Cool   Normal   True       Yes
7      Rainy  Mild     High  False        No
8      Rainy  Cool   Normal  False       Yes
9      Sunny  Mild   Normal  False       Yes
10     Rainy  Mild   Normal   True       Yes
11  Overcast  Mild     High   True       Yes
12  Overcast   Hot   Normal  False       Yes
13     Sunny  Mild     High   True        No
14     Rainy   Hot     High  False        No
15     Rainy   Hot     High   True        No
16  Overcast   Hot     High  False       Yes
17     Sunny  Mild     High  False       Yes
18     Sunny  Cool   Normal  False       Yes
19     Sunny  Cool   Normal   True        No
20  Overcast  Cool   Normal   True       Yes
21     Rainy  Mild     High  False        No
22     Rainy  Cool   Normal  False       Yes
23     Sunny  Mild   Normal  False       Yes
24     Rainy  Mild   Normal   True       Yes
25  Overcast  Mild     High   True       Yes
26  Overcast   Hot   Normal  False       Yes
27     Sunny  Mild     High   True        No
28     Rainy   Hot     High  False        No
29     Rainy   Hot     High   True        No
30  Overcast   Hot     High  False       Yes
31     Sunny  Mild     High  False       Yes
32     Sunny  Cool   Normal  False       Yes
33     Sunny  Cool   Normal   True        No
34  Overcast  Cool   Normal   True       Yes
35     Rainy  Mild     High  False        No
36     Rainy  Cool   Normal  False       Yes
37     Sunny  Mild   Normal  False       Yes
38     Rainy  Mild   Normal   True       Yes
39  Overcast  Mild     High   True       Yes
40  Overcast   Hot   Normal  False       Yes
41     Sunny  Mild     High   True        No

In [38]:
data.Outlook.unique()

array(['Rainy', 'Overcast', 'Sunny'], dtype=object)

In [39]:
data.Temp.unique()

array(['Hot', 'Mild', 'Cool'], dtype=object)

In [40]:
data.Humidity.unique()

array(['High', 'Normal'], dtype=object)

In [41]:
data.Windy.unique()

array([False,  True])

In [42]:
data.isna().sum()

Outlook      0
Temp         0
Humidity     0
Windy        0
Play Golf    0
dtype: int64

In [43]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder() #label encoder encodes the categorical labels into numerical labels starts from 0,1,2...
for x in data:
    data[x] = le.fit_transform(data[x])

In [44]:
data.shape

(42, 5)

In [45]:
X = data.drop("Play Golf",axis=1)
y = data['Play Golf']

In [55]:
from sklearn.model_selection import train_test_split #this funciton split x and y randomnly-
#so for each time the output will be diffrent.to keep the data consistant we have to set a seed.random_state!=0, we are setting a seed.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.50,random_state=42) #0.20 data will be for training.

In [64]:
X_train.shape

(21, 4)

In [56]:
from sklearn.naive_bayes import GaussianNB
naive_classifier = GaussianNB()

In [57]:
?naive_classifier

In [58]:
naive_classifier.fit(X_train,y_train)

GaussianNB()

In [59]:
y_pred=naive_classifier.predict(X_test)

In [60]:
y_pred

array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1])

In [61]:
y_test

25    1
13    0
8     1
26    1
4     1
39    1
19    0
29    0
30    1
6     1
27    0
12    1
17    1
9     1
15    0
33    0
16    1
36    1
35    0
0     0
24    1
Name: Play Golf, dtype: int64

In [62]:
#confusison matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred) #only the diagonal values are true predicitons.

array([[ 6,  2],
       [ 1, 12]])

In [63]:
#accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8571428571428571

In [21]:
#END